"""Emit the measured Table 6 (LaTeX + CSV) and the H1/H2/H3 verdict block."""
from __future__ import annotations

from .stats import PairStat, benjamini_hochberg

ROW_LABEL = {
    "token_surface": "Token surface",
    "semantic_classification": "Semantic classification",
    "first_token_distribution": "First-token distribution",
    "perturbation_stability": "Perturbation stability",
    "internal_representations": "Internal representations",
}


def _star(ci: tuple[float, float]) -> str:
    lo, hi = ci
    if lo > 0:
        return r"$\uparrow$"
    if hi < 0:
        return r"$\downarrow$"
    return ""


def table6_latex(pairs: list[PairStat], rows: dict[str, str]) -> str:
    qvals = benjamini_hochberg([p.phi_p_value for p in pairs])
    lines = [
        r"% Measured Table 6. Generated by dcorr.analysis.tables - do not hand-edit.",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"Defense pair & Rows & $\hat p_1$ & $\hat p_2$ & $\hat\phi$ (95\% CI) & $\Delta$ (95\% CI) & $q$ \\",
        r"\midrule",
    ]
    for p, q in zip(pairs, qvals):
        rowtag = "same" if p.same_row else "cross"
        r1 = ROW_LABEL.get(rows.get(p.d1, ""), rows.get(p.d1, "?"))
        r2 = ROW_LABEL.get(rows.get(p.d2, ""), rows.get(p.d2, "?"))
        rowcell = r1 if p.same_row else f"{r1} $\\times$ {r2}"
        lines.append(
            f"{p.d1} $\\times$ {p.d2} & {rowcell} ({rowtag}) & "
            f"{p.p1:.2f} & {p.p2:.2f} & "
            f"{p.phi:.2f} [{p.phi_ci[0]:.2f}, {p.phi_ci[1]:.2f}] {_star(p.phi_ci)} & "
            f"{p.excess:.3f} [{p.excess_ci[0]:.3f}, {p.excess_ci[1]:.3f}] & "
            f"{q:.3f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def table6_csv(pairs: list[PairStat]) -> str:
    qvals = benjamini_hochberg([p.phi_p_value for p in pairs])
    head = ("d1,d2,same_row,n,p1,p2,joint,indep,excess,phi,phi_lo,phi_hi,"
            "excess_lo,excess_hi,phi_p,bh_q")
    out = [head]
    for p, q in zip(pairs, qvals):
        out.append(",".join(str(x) for x in [
            p.d1, p.d2, int(p.same_row), p.n, f"{p.p1:.4f}", f"{p.p2:.4f}",
            f"{p.joint:.4f}", f"{p.indep:.4f}", f"{p.excess:.4f}", f"{p.phi:.4f}",
            f"{p.phi_ci[0]:.4f}", f"{p.phi_ci[1]:.4f}",
            f"{p.excess_ci[0]:.4f}", f"{p.excess_ci[1]:.4f}",
            f"{p.phi_p_value:.4g}", f"{q:.4g}",
        ]))
    return "\n".join(out)


def hypothesis_verdicts(pairs: list[PairStat], headline: list[list[str]],
                        phi_null_band: float = 0.15) -> dict:
    """Apply the pre-registered decision rules to each headline pair."""
    by_key = {frozenset((p.d1, p.d2)): p for p in pairs}
    verdicts = {}
    for pr in headline:
        key = frozenset(pr)
        p = by_key.get(key)
        if p is None:
            verdicts["_".join(pr)] = {"error": "pair not found in results"}
            continue
        if p.same_row:
            supported = p.phi_ci[0] > 0 and p.excess_ci[0] > 0
            verdicts["_".join(pr)] = {
                "hypothesis": "H1", "pair": pr, "same_row": True, "phi": p.phi,
                "phi_ci": list(p.phi_ci), "excess": p.excess, "excess_ci": list(p.excess_ci),
                "supported": bool(supported),
            }
        else:
            contains_zero = p.phi_ci[0] <= 0 <= p.phi_ci[1]
            supported = contains_zero and abs(p.phi) < phi_null_band
            underpowered = contains_zero and abs(p.phi) >= phi_null_band
            verdicts["_".join(pr)] = {
                "hypothesis": "H2", "pair": pr, "same_row": False, "phi": p.phi,
                "phi_ci": list(p.phi_ci),
                "supported": bool(supported), "underpowered": bool(underpowered),
            }
    return verdicts
