"""Blank every FRR value in a fusion_results.tex produced without real benign data.

fusion_analysis.py requires --refusal, and all of its ASR and diversity output depends
only on --breach. When the per-prompt benign vectors are not available the run is still
valid for everything breach-derived, but the FRR column is then computed from a
placeholder and would render as a plausible-looking 0.000 in the manuscript.

This pass replaces those cells with the script's own missing-value marker (--) and stamps
a banner on the file. It is a safety net, not part of the analysis: once
fusion/refusal.csv holds real data, re-run fusion_analysis.py and skip this entirely.

Usage:  python scripts/strip_placeholder_frr.py fusion/fusion_results.tex
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BANNER = (
    "% WARNING: this file was generated WITHOUT per-prompt benign refusal data.\n"
    "% Every FRR cell has been blanked to -- by scripts/strip_placeholder_frr.py.\n"
    "% ASR, phi, Q, disagreement and double-fault are real and unaffected.\n"
    "% Supply fusion/refusal.csv and re-run fusion_analysis.py to fill the FRR column.\n"
)

NUMERIC = re.compile(r"[0-9.]+\Z")

# Column layouts are fixed by fusion_analysis.write_tex(): the combination-rules table is
# (rule, ASR, FRR); the selection table is (size, ASR, FRR, ASR, FRR).
FRR_COLUMNS = {"tab:combrules": (2,), "tab:selection": (2, 4)}


def strip(path: Path) -> tuple[int, int]:
    label, macros, cells = None, 0, 0
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if "label{tab:" in line:
            label = line.split("label{", 1)[1].split("}", 1)[0]

        if line.startswith("\\newcommand") and "FRR}{" in line:
            head, _, _ = line.partition("FRR}{")
            line = head + "FRR}{--}"
            macros += 1
        elif line.rstrip().endswith("\\\\") and "&" in line:
            parts = [p.strip() for p in line.rstrip()[:-2].split("&")]
            hit = False
            for i in FRR_COLUMNS.get(label, ()):
                if i < len(parts) and NUMERIC.match(parts[i]):
                    parts[i] = "--"
                    hit = True
            if hit:
                cells += 1
                line = " & ".join(parts) + " \\\\"
        out.append(line)

    path.write_text(BANNER + "\n".join(out) + "\n", encoding="utf-8")
    return macros, cells


if __name__ == "__main__":
    for p in sys.argv[1:]:
        mac, cel = strip(Path(p))
        print(f"{p}: blanked {mac} FRR macros, {cel} table rows")
